### ISSUE TITLE
The location you entered was not found.

### ISSUE THREAD

**Issue by dcsimm9** [Cyndakwil/Wallpaper-Wizard#10]
I will put my city in the location and things will work fine for about a day and then I get this pop up asking me to check the spelling.  As of today, after closing this pop up window the program will crash and I can't edit the location
![wallpwiz](https://user-images.githubusercontent.com/69493492/89851540-53ec0780-db52-11ea-905e-1cf27e6a6bb7.png)

**Comment by rohan-shettyy** [comment]
Firstly, please make sure you have the newest release from [the download page](https://cyndakwil.itch.io/wallpaper-wizard). 
Also, I am aware of this issue and I'm working on a fix. I am exceeding the API limit due to the number of users using the app at the same time, so please bear with me as I figure out a solution.

**Comment by dcsimm9** [comment]
Thanks for the quick response, I hadn't realized an update came out just a week after I downloaded it.  I believe that update solved it but I will let you know if it continues to happen.  Thanks again :)
